use_frameworks!

target 'CRToast_Example' do
  pod 'CRToast', :path => '../'

  target 'CRToast_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
